name: Analyse automatique de la Pull Request/Issue

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name:
        working-directory: .github/scripts
        run: |
          npm init -y
          npm install @octokit/auth-app @octokit/rest @actions/github typescript @types/node --save-dev
      
      - name: Build TypeScript
        working-directory: .github/scripts
        run: npx tsc ./index.ts ./utils/file-related.ts ./utils/auto-label.ts ./utils/check-description.ts --outDir dist --module commonjs --target ES2020 --esModuleInterop

      - name: Run Checks
        working-directory: .github/scripts
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          APP_ID: ${{ secrets.APP_ID }}
          INSTALL_ID: ${{ secrets.INSTALL_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: node dist/index.js